//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.24 at 04:27:32 ���� CST 
//


package when_how.hero.hibernate.hql;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hibernate.when_how.com.hql package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Hqls_QNAME = new QName("http://com.when_how.hibernate/hql", "hqls");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hibernate.when_how.com.hql
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Hql }
     * 
     */
    public Hql createHql() {
        return new Hql();
    }

    /**
     * Create an instance of {@link Hqls }
     * 
     */
    public Hqls createHqls() {
        return new Hqls();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Hqls }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com.when_how.hibernate/hql", name = "hqls")
    public JAXBElement<Hqls> createHqls(Hqls value) {
        return new JAXBElement<Hqls>(_Hqls_QNAME, Hqls.class, null, value);
    }

}
