//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.24 at 04:27:32 ���� CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.when_how.hibernate/hql", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package when_how.hero.hibernate.hql;
